### ISSUE TITLE
Ranking on EvalAI leaderboard

### ISSUE THREAD

**Issue by esborisova** [oasisresearchlab/context24#5]
Hi!

It seems that the ranking on the leaderboard for Task 1 is based on the logic "the lower nDCG@5 and nDCG@10 scores, the better". Should not it be the opposite? Could you please elaborate a bit on the evaluation strategy?

Thanks in advance!

**Comment by aakanksha19** [comment]
Hi, thanks a lot for raising this! Looks like evalAI's default way to produce a leaderboard ranking is to sort by ascending order of metric value, which is incorrect in this case since higher nDCG scores are better. We've fixed this to show the correct leaderboard ranking now! Submissions with higher nDCG@10 scores are ranked higher.

Please let us know if you find any other issues!
