### ISSUE TITLE
Task 1: Prediction file

### ISSUE THREAD

**Issue by esborisova** [oasisresearchlab/context24#6]
Hello! 

I am tackling the task as a binary classification problem. I am not sure whether the final prediction file should also contain rows with claim ids which have empty predictions (none of the figs/tabs were predicted as providing evidence, i.e., assigned class 0).  So far, I generated files containing only claims with predictions (fig/tabs providing evidence, i.e., assigned class 1).

Are such empty rows considered during evaluation or is it fine to exclude them?

Thanks!

Edited: I have some concerns about the scores obtained. For some reason, in case when my prediction file contains only 8 rows (excluding headers) with the predictions (no rows with empty predictions), the scores are considerably higher compared to cases when the file has 30 and more rows. Even if the predictions in the second scenario are worse, I would still expect the scores for the first case to be quite low and without such a large difference compared to the other.

**Comment by ArneBinder** [comment]
Looking at the eval script, it seems to be quite strange that in [this line](https://github.com/oasisresearchlab/context24/blob/5b494bd6dddf603ae950fbb6ca9cfd0a1cf30a58/eval/task1_eval.py#L81), the score gets normalized by `non_empty_samples` which depends on the **predicted** labels. This has the strange side-effect that you do not consider gold entries where no evidence was found (if there are no empty prediction rows in the file as @esborisova has assembled her output). So, why not normalizing by this instead:
```python
# number of gold samples that have evidence
non_empty_gold_samples = len(claim_id for claim_id, images in gold_labels.items() if len(images) > 0)
```

**Comment by aakanksha19** [comment]
Thanks for raising these points @esborisova and @ArneBinder ! 

The dataset **should not contain any gold entries where no associated evidence was found**, since all claims were written based off of figures/tables present in our paper set (let us know if you've spotted issues here). The only reason for adding [this check](https://github.com/oasisresearchlab/context24/blob/5b494bd6dddf603ae950fbb6ca9cfd0a1cf30a58/eval/task1_eval.py#L45-L47) in the eval script was for us to double-check that we had correctly processed and added evidence associated with every gold claim since we were actively updating training data at the time. As you said, we can remove this check now, but this should not be affecting scores in any way.

However, the way we're computing `non_empty_samples` is probably what's affecting your scores. We were making the assumption that every claim ID would be included in the submitted predictions file and so `non_empty_samples` would ultimately be equal to `num_gold_samples`. But if claim IDs are skipped/missing in the predictions file, then the normalization will be incorrect since the denominator is much smaller than it should be. Your suggestion of normalizing by the gold dataset size, and removing dependency on prediction file size, is the right way to resolve this. I will make these updates to the eval script as well as the eval AI leaderboard later today.

Please let us know if you find any more issues!

**Comment by esborisova** [comment]
@aakanksha19 Thanks for fixing this. Will we need to re-upload all the submissions or will the updated evaluation be re-run automatically?

**Comment by aakanksha19** [comment]
@esborisova This has now been fixed both in the eval script as well as on evalAI! You don't need to re-upload your submissions, I will re-run the updated evaluation from our side on affected submissions once the challenge portal closes. Let us know if you have any more questions!
